name: map_plugin
description: A Flutter plugin for integrating  Maps in Android applications with Multiple Markers.
version: 0.0.2
homepage: https://github.com/hello-addweb/map_package.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.0
  google_maps_flutter_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.6.0
  pedantic: ^1.8.0
  plugin_platform_interface: ^1.0.2
  mockito: ^4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.search.map_plugin
        pluginClass: MapPlugin
      ios:
        pluginClass: MapPlugin

